#!/bin/bash

# Copyright (c) 2011-2013 Peng Sun. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the COPYRIGHT file.

# script to setup swig of web10g measurement

swig -c++ -python -o web10g_measure_wrap.cpp web10g_measure.i
python setup_web10g_measure.py build_ext --inplace
