#! /bin/bash


# Copyright (c) 2011-2013 Peng Sun. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the COPYRIGHT file.

# script to setup swig

./swig_dir_service
./swig_web10g_measure
